# Generated by Django 3.2 on 2021-10-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_chore_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='completed_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='chore',
            name='imagen',
            field=models.ImageField(upload_to='app'),
        ),
    ]
