# Generated by Django 3.2 on 2021-10-22 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211022_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chore',
            name='completed_time',
        ),
    ]
