# Generated by Django 3.2 on 2021-10-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_chore_louischore'),
    ]

    operations = [
        migrations.CreateModel(
            name='katieChore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='app')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'chore',
                'verbose_name_plural': 'chores',
            },
        ),
        migrations.CreateModel(
            name='vickyChore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='app')),
                ('description', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'chore',
                'verbose_name_plural': 'chores',
            },
        ),
    ]
