# Generated by Django 3.2 on 2021-10-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_katiechore_vickychore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katiechore',
            name='imagen',
            field=models.ImageField(null=True, upload_to='app'),
        ),
    ]
