# Generated by Django 3.2 on 2021-10-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_katiechore_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vickychore',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
