# Generated by Django 3.2 on 2021-10-22 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_alter_vickychore_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='app')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'chore',
                'verbose_name_plural': 'chores',
            },
        ),
        migrations.CreateModel(
            name='UserChore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'UserChore',
                'verbose_name_plural': 'UserChores',
            },
        ),
        migrations.DeleteModel(
            name='katieChore',
        ),
        migrations.DeleteModel(
            name='louisChore',
        ),
        migrations.DeleteModel(
            name='vickyChore',
        ),
        migrations.AddField(
            model_name='chore',
            name='userchore',
            field=models.ManyToManyField(to='app.UserChore'),
        ),
    ]
