# Generated by Django 3.2 on 2021-10-24 21:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211022_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='CompletedTask',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chore',
            name='StartTask',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
