# Generated by Django 3.2 on 2021-10-25 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20211024_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chore',
            name='CompletedTask',
        ),
        migrations.AddField(
            model_name='chore',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chore',
            name='StartTask',
            field=models.DateField(blank=True, null=True),
        ),
    ]
