# Generated by Django 3.2 on 2021-10-25 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20211025_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chore',
            name='timestamp',
        ),
    ]
