# Generated by Django 3.2 on 2021-11-01 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_chore_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='Event Name')),
                ('event_date', models.DateTimeField(verbose_name='Event')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='chore',
            options={'ordering': ['name'], 'verbose_name': 'chore', 'verbose_name_plural': 'chores'},
        ),
        migrations.AlterModelOptions(
            name='userchore',
            options={'ordering': ['name'], 'verbose_name': 'UserChore', 'verbose_name_plural': 'UserChores'},
        ),
        migrations.RemoveField(
            model_name='chore',
            name='StartTask',
        ),
        migrations.AddField(
            model_name='userchore',
            name='gener',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userchore',
            name='lastName',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chore',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='chore',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chore',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Updated date'),
        ),
    ]
