# Generated by Django 3.2 on 2021-11-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20211101_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchore',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
