# Generated by Django 3.2 on 2021-11-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_userchore_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='state',
            field=models.BooleanField(default=True, verbose_name='State'),
        ),
    ]
