# Generated by Django 3.2 on 2021-11-08 04:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_chore_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchore',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userchore',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fechad de Creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userchore',
            name='state',
            field=models.BooleanField(default=True, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='chore',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='chore',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Chore name'),
        ),
        migrations.AlterField(
            model_name='userchore',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Username'),
        ),
    ]
