# Generated by Django 3.2 on 2021-11-10 21:09

import ckeditor.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20211107_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='content',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now, verbose_name='Contenido'),
            preserve_default=False,
        ),
    ]
