# Generated by Django 3.2 on 2021-11-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20211111_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='startTask',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
