# Generated by Django 3.2 on 2021-11-12 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_chore_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chore',
            old_name='startTask',
            new_name='start_task',
        ),
    ]
