# Generated by Django 3.2 on 2021-11-15 07:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_rename_starttask_chore_start_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='imagen',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='app'),
            preserve_default=False,
        ),
    ]
